/* @flow */

export default {
  root: {
    background: '#FFF',
    display: 'inline-block',
  },
  popover: {
    marginTop: 10,
    background: '#FFF',
    position: 'absolute',
    height: 250,
    width: 225,
    borderRadius: 4,
    padding: 10,
    WebkitBoxShadow: '0px 4px 30px 0px rgba(220,220,220,1)',
    MoxBoxShadow: '0px 4px 30px 0px rgba(220,220,220,1)',
    boxShadow: '0px 4px 30px 0px rgba(220,220,220,1)',
  },
  button: {
    backgroundColor: '#fdfdfd',
    border: '1px solid #bbb',
    padding: 0,
    color: '#888',
    margin: 0,
    borderRadius: 20,
    lineHeight: '1.0em',
    cursor: 'pointer',
    height: 40,
    paddingLeft: 14,
    paddingRight: 18,
  },
  bottomGradient: {
    width: '100%',
    height: '1em',
    position: 'absolute',
    bottom: '0px',
    left: '0px',
    right: '0px',
    backgroundColor: 'white',
    pointerEvents: 'none',
    background: 'linear-gradient(to bottom, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%)',
    filter: "progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff', GradientType=0 )",
  },
  stickerList: {
    position: 'absolute',
    overflowX: 'none',
    overflowY: 'scroll',
    top: '0px',
    bottom: '0px',
    left: '0px',
    right: '0px',
    padding: 10,
  },
  icon: {
    fontSize: '1.6em',
    lineHeight: '1.2em',
  },
  buttonText: {
    position: 'relative',
    top: '-3px',
    left: '5px',
  },
};
