blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://draftjs.herokuapp.com/
    about: "Join the channel #draft-js-plugins after signing into the DraftJS Slack organization"
